replicaCount: 1

image:
  repository: <image-name>
  pullPolicy: Always
  tag: <image-tag>

imagePullSecrets: 
  - name: regcred
nameOverride: "go-calc-app"
fullnameOverride: "go-calc-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "go-calc-chart"

podAnnotations: {}

podSecurityContext: {}
    

securityContext: {}


service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}